### ISSUE TITLE
Text box appears in piano game

### ISSUE THREAD

**Issue by karrylarry23** [multimokia/MAS-Submod-consistent-menus#1]
There's a minor bug where a pink text box without any text appears whenever I try to play the piano. 

I attached images of the piano game with and without the submod.

Piano with submod:
![2020-07-16 (7)](https://user-images.githubusercontent.com/68371040/87642895-c510e880-c767-11ea-8a42-e2c732c3fffc.png)

Piano without submod:
![2020-07-16 (8)](https://user-images.githubusercontent.com/68371040/87643151-1ae59080-c768-11ea-8857-e1e75879a757.png)

**Comment by multimokia** [comment]
Noted, will push a fix. Thank you.

**Comment by multimokia** [comment]
The above commit fixes this issue. Thanks for reporting!

**Comment by multimokia** [comment]
Closing as resolved
