### ISSUE TITLE
Small hangman bug

### ISSUE THREAD

**Issue by lunulae** [multimokia/MAS-Submod-consistent-menus#3]
I'm not sure if you've already caught this one, but I noticed that in Hangman, after Monika asks if you want to play again, she stays in the center of the screen rather than back to the side away from the game window.
I'm not 100% sure if the cause is from this submod, but I figured I'd put it forward just in case.

**Comment by multimokia** [comment]
I may just push something to typos to manage this anyway. Kind of weird it doesn't just automatically handle this

**Comment by multimokia** [comment]
This has been addressed as of MAS 0.11.4
